@url = http://localhost:64000/employees
@employeeId = b3fde8de-e428-40ca-abf5-08a58cdb8f88
@employeeToDeleteId = 0f481564-be79-476c-84c8-f3bfb05c5f4c


GET {{url}}

# GET  {{url}}/{{employeeId}}

# POST {{url}}
# content-type: application/json

# {
#     "lastName": "Kowalski",
#     "firstName": "Dariusz",
#     "secondName": "Andrzej",
#     "dateOfBirth": "2001-04-03",
#     "pesel": "65232487341",
#     "gender": "Male"
# }

# PUT {{url}}
# content-type: application/json

# {
#     "id": "0f481564-be79-476c-84c8-f3bfb05c5f4c",
#     "lastName": "Kowalsky",
#     "firstName": "Marek",
#     "secondName": "Mariusz",
#     "dateOfBirth": "2001-01-01",
#     "pesel": "97844232487",
#     "gender": "Female"
# }

# DELETE {{url}}/{{employeeToDeleteId}}
